---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: ''
polling_url: ''
polling_headers: ''
custom_fields:
- keyname: api_key
  field_type: string
  name: API Key
  description: Your LastFM API Key
- keyname: username
  field_type: string
  name: Username
- keyname: locale
  field_type: select
  options:
  - en-EN
  - fr-FR
  default: en-EN
  name: Locale
  description: Select locale for number display
name: LastFM
refresh_interval: 15
