---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "https://ws.audioscrobbler.com/2.0/?method=user.getInfo&user={{username}}&api_key={{api_key}}&format=json\r\nhttps://ws.audioscrobbler.com/2.0/?method=user.getRecentTracks&user={{username}}&api_key={{api_key}}&format=json&limit=1\r\nhttps://ws.audioscrobbler.com/2.0/?method=user.getlovedtracks&user={{username}}&api_key={{api_key}}&format=json&limit=50&page=1"
polling_headers: ''
custom_fields:
- keyname: api_key
  field_type: string
  name: API Key
  description: Your LastFM API Key - Get your api key <a href="https://www.last.fm/api"
    class="underline" target="_blank">here</a>."
  placeholder: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- keyname: username
  field_type: string
  name: Username
- keyname: locale
  field_type: select
  options:
  - en-EN
  - fr-FR
  default: en-EN
  name: Locale
  description: Select locale for number display
name: LastFM
refresh_interval: 15
